### ISSUE TITLE
Boilerplate.html menu broken

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-style#196]
After IE code fixes for the forEach() and closest() updates, the submenus are no longer working.

**Comment by bignamehere** [comment]
Bug fixes implemented and code cleaned up.

closing as per [
6b1651d](https://github.com/USDA-FSA/fsa-style/commit/6b1651dbdcd62c0632b3192f2ec47876f8517695) and [cf12ca8](https://github.com/USDA-FSA/fsa-style/commit/cf12ca8ba8c7e3ef9467575599006a63e0eec7fd)

**Comment by francisrupert** [comment]
@bignamehere,

I've added Header and Footer components to `index.html` on `develop` branch.

**One additional scripting request:** You'll notice I have multiple examples and states listed (attached). I would like the interactivity to **not work** at all solely on `index.html` since I want to show the expanded states.

Probably the easiest "hook" is "if `<body>` has `class="docs__page"` then don't execute any of `fsa-nav-global.js`'s functions.

**Comment by bignamehere** [comment]
Added bug fix and also disabled menu with the presence of the docs class.

closed via [87e9e7d](https://github.com/USDA-FSA/fsa-style/commit/87e9e7d2b52e20642760cb450ca3be46558d7afa) and [90a5872](https://github.com/USDA-FSA/fsa-style/commit/90a5872a1ceefc6790fede4522f7b2c8bd3ad613)
