### ISSUE TITLE
Vanilla-ize Stepped Control JS

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#237]
https://github.com/USDA-FSA/fsa-style/blob/master/src/js/components/fsa-stepped-control.js

**Comment by bignamehere** [comment]
@francisrupert I have updated the JS for the stepped control in WP4 version(c4b9e03) and got it working and copied to the feature branch (1a6d10c).

Can you take a look at the feature branch and see if it is working properly?

**Comment by francisrupert** [comment]
Yup, worked perfectly on the feature branch. I'll stress-test it a bit more (including browsers), but on the surface it is identical to my jQuery initial take.

And I've moved to [2.1.5 Milestone](https://github.com/USDA-FSA/fsa-style/milestone/16).

**Comment by francisrupert** [comment]
It doesn't appear to be working in the **Modal**, even though I see you have...

https://github.com/USDA-FSA/fsa-style/blob/1a6d10cb8522a2650923dcdfbb4dcc83248f1256/src/js/components/fsa-stepped-control.js#L48-L51

**Comment by bignamehere** [comment]
@francisrupert I will look into it, and see why it isn't working. Probably has something to do with `.fsa-modal` being used in multiple spots on the kitchen sink. Might need to target more specifically.

**Comment by bignamehere** [comment]
@francisrupert Made the change to fix the modal listener. 835edd0 

take a look and let me know if I should merge to develop.

**Comment by francisrupert** [comment]
Modal's listener works and this Vanilla JS is awesome. Move to `develop` and close this Issue at your discretion.

**Comment by bignamehere** [comment]
@francisrupert I merged into Develop, but I can't test it with my setup. Can you pull it down and take a look? Assigning to you.

**Comment by francisrupert** [comment]
@bignamehere, 

Yup, works perfectly on `develop`.

### Feedback

What do you think of renaming `setComponentStyle()` to something more specific, like `steppedControl()`, as it was in the original jQuery? `setComponentStyle()` might be too abstract. 

### Meanwhile

Now that we've got a much more mature set of vanilla scripting going on, is now the time to optimize? Nothing major, if only for the **utility methods** repeated across them, e. g. `forEach`, `getClosest`. 

Resulting in something like `var FSA_PROTOTYPE_UTILITIES = require('./core/fsa-prototype-utilities');`

Create an Issue for that if you like.

**Comment by bignamehere** [comment]
@francisrupert  JavaScript methods should be named in a way that explains what it is doing, so that when someone looks over the code, they have an understanding (at that point in the code) about what will take place if the method is called. `steppedControl()` provides no indication as to what it does, and actually follows the best practice of a Class naming convention.... like `var sc = new SteppedControl();`  Classes should be nouns, and methods should be verbs. There are obviously exceptions, but in general the use of setXYZ or getXYZ should be used to "set" something or "get" a returned variable. Since we are setting the components style, I thought it was pretty good from a naming perspective. 

We could argue that `setComponentStyle()` might be too general, but at that point in the code, we don't know what is going to happen from a style perspective. So if we name it something very specific like, `setColorToBlue()` then you have to rewrite your code and change the method names when you change it to red or enlarge the item as well. Now, if I would have used `setComponent()`, then there is certainly an argument for being too abstract.

I like the idea of creating a small utility Class, so I will create the issue.

Thanks for testing it!

**Comment by francisrupert** [comment]
Agree with all of that 100%. 

I was thinking more about the reason we renamed Growl's and Modal's `show()` and `dismiss()` to `growl__show()`/`growl__dismiss()` and `modal__show()`/`modal__dismiss()`.

**Comment by bignamehere** [comment]
Ah yes, for namespacing. I'm not opposed to that, it just seems a tad verbose with any modern tooling being able to minify and keep namespacing. I can reopen and drop those in there to be consistent with how the other methods are named.

**Comment by bignamehere** [comment]
@francisrupert I made namespacing updates, but can't test locally. Can you review and see if any JS error come up from me missing a name?

**Comment by francisrupert** [comment]
@bignamehere,

I tested all the components' JS and corrected one instance of a minor misspelling, on https://github.com/USDA-FSA/fsa-style/commit/3e71c5ced29985107bdda60af300b5313948e773.

Everything else is good. I'm squeezing in the Stepped Tabs (#181) for this [2.1.5 milestone ](https://github.com/USDA-FSA/fsa-style/milestone/16), and will look to publish 2.1.5**-RC1** soon and test.
